# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'List.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(515, 435)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 141, 20))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(170, 30, 131, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.Add = QtWidgets.QPushButton(Dialog)
        self.Add.setGeometry(QtCore.QRect(180, 80, 113, 32))
        self.Add.setObjectName("Add")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(305, 30, 191, 121))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.Add_2 = QtWidgets.QPushButton(Dialog)
        self.Add_2.setGeometry(QtCore.QRect(300, 160, 61, 32))
        self.Add_2.setObjectName("Add_2")
        self.Add_3 = QtWidgets.QPushButton(Dialog)
        self.Add_3.setGeometry(QtCore.QRect(350, 160, 71, 32))
        self.Add_3.setObjectName("Add_3")
        self.Add_4 = QtWidgets.QPushButton(Dialog)
        self.Add_4.setGeometry(QtCore.QRect(420, 160, 81, 32))
        self.Add_4.setObjectName("Add_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Your favorite food item"))
        self.Add.setText(_translate("Dialog", "Add"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Dialog", "Choco bar"))
        item = self.listWidget.item(1)
        item.setText(_translate("Dialog", "Mangoes"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.Add_2.setText(_translate("Dialog", "Edit"))
        self.Add_3.setText(_translate("Dialog", "Delete"))
        self.Add_4.setText(_translate("Dialog", "Delete All"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
